# Generated by Django 5.2 on 2025-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passport_no', models.CharField(max_length=50, unique=True)),
                ('visa_no', models.CharField(max_length=50, unique=True)),
                ('emirates_id_number', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('insurance_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passport_expiry', models.DateField()),
                ('visa_expiry', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emergency_contact', models.CharField(max_length=255)),
                ('insurance_expiry', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('home_address', models.TextField()),
                ('uae_address', models.TextField()),
            ],
            options={
                'verbose_name': 'Staff Detail',
                'verbose_name_plural': 'Staff Details',
            },
        ),
    ]
