# Generated by Django 5.2 on 2025-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='staff_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
