# Generated by Django 5.2 on 2025-05-10 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_staffdetails_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
