# Generated by Django 5.2 on 2025-05-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_staffdetails_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='visa_status',
            field=models.CharField(choices=[('Renewed', 'Renewed'), ('In Progress', 'In Progress'), ('Expired', 'Expired'), ('Expiring Soon', 'Expiring Soon'), ('New Visa', 'New Visa')], default='New Visa', max_length=20),
        ),
    ]
