# Generated by Django 5.2 on 2025-05-10 07:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='joining_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('submitted_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected')], default='Under Review', max_length=20)),
                ('gm_status', models.CharField(choices=[('Approved', 'Approved'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('mgmt_status', models.CharField(choices=[('Approved', 'Approved'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='HR.staffdetails')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
            },
        ),
        migrations.CreateModel(
            name='LeaveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commenter', models.CharField(max_length=100)),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='HR.leaverequest')),
            ],
            options={
                'verbose_name': 'Leave Comment',
                'verbose_name_plural': 'Leave Comments',
            },
        ),
    ]
