# Generated by Django 5.2 on 2025-05-12 07:11

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_alter_staffdetails_joining_date_leaverequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('loan_status', models.CharField(choices=[('Approved', 'Approved'), ('Cleared', 'Cleared'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('gm_status', models.CharField(choices=[('Approved', 'Approved'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('mgmt_status', models.CharField(choices=[('Approved', 'Approved'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='HR.staffdetails')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.CreateModel(
            name='LoanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commenter', models.CharField(max_length=100)),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='HR.loan')),
            ],
            options={
                'verbose_name': 'Loan Comment',
                'verbose_name_plural': 'Loan Comments',
            },
        ),
    ]
