# Generated by Django 5.2 on 2025-05-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_loan_loancomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='submitted_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
