# Generated by Django 5.2 on 2025-05-12 07:48

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_overtime_overtimecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('gm_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('mgmt_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('submitted_by', models.CharField(max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='HR.staffdetails')),
            ],
            options={
                'verbose_name': 'Fine',
                'verbose_name_plural': 'Fines',
            },
        ),
        migrations.CreateModel(
            name='FineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commenter', models.CharField(max_length=100)),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='HR.fine')),
            ],
            options={
                'verbose_name': 'Fine Comment',
                'verbose_name_plural': 'Fine Comments',
            },
        ),
    ]
