# Generated by Django 5.2 on 2025-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0011_appraisal_appraisalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='staff_type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Manpower', 'Manpower')], default='Staff', max_length=20),
        ),
    ]
