# Generated by Django 5.2 on 2025-05-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
    ]
