# Generated by Django 5.2 on 2025-05-14 06:41

import django.db.models.deletion
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(default=inventory.models.generate_request_no, max_length=5, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('local', 'Local'), ('imported', 'Imported')], max_length=10)),
                ('removal_type', models.CharField(choices=[('sales', 'Sales'), ('deadstock', 'Deadstock')], max_length=20)),
                ('accounts_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('underreview', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('gm_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('underreview', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('mgmt_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('underreview', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('gm_remarks', models.TextField(blank=True)),
                ('mgmt_remarks', models.TextField(blank=True)),
                ('products', models.ManyToManyField(related_name='removal_requests', to='inventory.product')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Removal Requests',
            },
        ),
    ]
