# Generated by Django 5.2 on 2025-05-14 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_removalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='removalrequest',
            name='products',
        ),
        migrations.CreateModel(
            name='RemovalRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_request_items', to='inventory.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.removalrequest')),
            ],
            options={
                'verbose_name_plural': 'Removal Request Items',
            },
        ),
    ]
