# Generated by Django 5.2 on 2025-05-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_removalrequest_products_removalrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='removalrequest',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
