# Generated by Django 5.2 on 2025-04-29 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('contact_email', models.EmailField(max_length=254)),
                ('company_number', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=100)),
                ('license_expiry_date', models.DateField()),
                ('tirn_number', models.CharField(max_length=100)),
                ('license_file', models.FileField(upload_to='licenses/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
