# Generated by Django 5.2 on 2025-04-30 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_inquiry_assign_to_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quote_title', models.CharField(max_length=255)),
                ('cargo_body', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('quote_no', models.CharField(max_length=100, unique=True)),
                ('qty', models.IntegerField()),
                ('product', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True)),
                ('unit_price', models.FloatField()),
                ('vat_applicable', models.BooleanField(default=False)),
                ('vat_percentage', models.FloatField(default=0)),
                ('subtotal', models.FloatField()),
                ('vat_amount', models.FloatField()),
                ('total', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('notes_remarks', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
