# Generated by Django 5.2 on 2025-04-30 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True)),
                ('qty', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.quote')),
            ],
        ),
    ]
