# Generated by Django 5.2 on 2025-04-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_quote_product_remove_quote_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='total',
        ),
    ]
