# Generated by Django 5.2 on 2025-04-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_quote_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='cargo_body',
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('closed', 'Closed')], default='new', max_length=10),
        ),
    ]
