# Generated by Django 5.2 on 2025-04-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_quote_cargo_body_alter_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
