# Generated by Django 5.2 on 2025-04-30 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_quote_invoice_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='invoice_pdf',
        ),
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('closed', 'Closed')], default='new', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('contact_email', models.EmailField(max_length=254)),
                ('mail_subject', models.CharField(max_length=255)),
                ('quote_no', models.CharField(max_length=100)),
                ('mail_body', models.TextField()),
                ('year', models.PositiveIntegerField(default=2025)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_mails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
