# Generated by Django 5.2 on 2025-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_quote_invoice_pdf_outgoingmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.DeleteModel(
            name='OutgoingMail',
        ),
    ]
