# Generated by Django 5.2 on 2025-05-01 05:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_quote_invoice_pdf_delete_outgoingmail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('draft', 'Draft'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('company_email', models.EmailField(max_length=254)),
                ('contact_email', models.EmailField(max_length=254)),
                ('mail_subject', models.CharField(max_length=255)),
                ('quote_no', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_mails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
