# Generated by Django 5.2 on 2025-05-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_outgoingmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmail',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingmail',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingmail',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingmail',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
