# Generated by Django 5.2 on 2025-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_outgoingmail_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmail',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('closed', 'Closed')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_no',
            field=models.CharField(max_length=5),
        ),
    ]
