# Generated by Django 5.2 on 2025-05-08 05:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_outgoingmail_status_alter_quote_quote_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('lpo_no', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('issue_date', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('cust_ref', models.CharField(blank=True, max_length=100)),
                ('our_ref', models.CharField(blank=True, max_length=100)),
                ('advance_amount', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('payment_terms', models.CharField(max_length=255)),
                ('delivery_terms', models.CharField(max_length=255)),
                ('omc_cost', models.FloatField(default=0)),
                ('subtotal', models.FloatField()),
                ('vat', models.FloatField()),
                ('net_total', models.FloatField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorp', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('service_title', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('rate', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('amount', models.FloatField()),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='sales.salesorder')),
            ],
        ),
    ]
