# Generated by Django 5.2 on 2025-05-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_salesorder_orderservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='order_no',
            field=models.CharField(default=12345, max_length=5),
            preserve_default=False,
        ),
    ]
