# Generated by Django 5.2 on 2025-05-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_salesorder_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='accounts_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='gm_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='mgmt_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('under_review', 'Under Review'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('job_card_created', 'Job Card Created'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_no',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
