# Generated by Django 5.2 on 2025-05-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_salesorder_accounts_status_salesorder_gm_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
