# Generated by Django 5.2 on 2025-05-08 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_salesorder_contact_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_order_number', models.CharField(max_length=5)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('delivered', 'Delivered')], default='in_progress', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.CharField(max_length=100)),
                ('specification', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='sales.jobcard')),
            ],
        ),
    ]
