# Generated by Django 5.2 on 2025-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_jobcard_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
