# Generated by Django 5.2 on 2025-05-08 11:56

from django.db import migrations, models
import random


def generate_job_card_no(apps, schema_editor):
    JobCard = apps.get_model('sales', 'JobCard')
    for job_card in JobCard.objects.all():
        max_attempts = 100
        for attempt in range(max_attempts):
            job_card_no = str(random.randint(10000, 99999))
            if not JobCard.objects.filter(job_card_no=job_card_no).exists():
                job_card.job_card_no = job_card_no
                job_card.save()
                break
        else:
            raise ValueError(f"Unable to generate unique job_card_no for JobCard ID {job_card.id} after {max_attempts} attempts.")


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_jobcard_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='JobCard',
            name='job_card_no',
            field=models.CharField(max_length=5, unique=True, blank=True, null=True),
        ),
        migrations.RunPython(generate_job_card_no, reverse_code=migrations.RunPython.noop),
    ]