# Generated by Django 5.2 on 2025-05-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_jobcard_job_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_no',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
